export const Colors = {
  primary: '#1A6BFF',
  primaryLight: '#E8F0FF',
  primaryDark: '#1152CC',
  secondary: '#0FD399',
  secondaryLight: '#E6FBF5',
  danger: '#FF4444',
  dangerLight: '#FFE8E8',
  warning: '#FF9500',
  warningLight: '#FFF3E0',
  info: '#1A6BFF',
  background: '#F5F7FA',
  surface: '#FFFFFF',
  surfaceHover: '#F9FAFB',
  border: '#E5E7EB',
  borderFocus: '#1A6BFF',
  textPrimary: '#111827',
  textSecondary: '#4B5563',
  textMuted: '#9CA3AF',
  textInverse: '#FFFFFF',
  overlay: 'rgba(0,0,0,0.5)',
  skeleton: '#E5E7EB',
} as const;
